<?xml version="1.0" encoding="Shift_JIS" ?> 

<!DOCTYPE books[
  <!ELEMENT books   (book+)>
  <!ELEMENT book    (title, price, caption)>
  <!ELEMENT title   (#PCDATA)>
  <!ELEMENT price   (#PCDATA)>
  <!ELEMENT caption (#PCDATA | em)*>
  <!ELEMENT em      (#PCDATA)>
]>

<books>
  <book>
    <title>Ç‚Ç≥ÇµÇ¢XML</title> 
    <price>330</price> 
    <caption>
      Ç∆ÇƒÇ‡Ç‚Ç≥ÇµÇ¢<em>XML</em>Ç≈Ç∑ÅB 
    </caption>
  </book>
  <book>
    <title>Ç‚Ç≥ÇµÇ¢Java</title> 
    <price>200</price> 
    <caption>
      Ç∆ÇƒÇ‡Ç‚Ç≥ÇµÇ¢<em>Java</em>Ç≈Ç∑ÅB 
    </caption>
  </book>
</books>
