<?xml version="1.0" encoding="Shift_JIS" ?> 

<!DOCTYPE books[
  <!ELEMENT books (book+)>
  <!ELEMENT book  (title, img)>
  <!ELEMENT title (#PCDATA)>
  <!ELEMENT img    EMPTY>
  <!ATTLIST img  file CDATA #IMPLIED>
]>

<books>
  <book>
    <title>‚â‚³‚µ‚¢XML</title> 
    <img file="xml.jpg"/> 
  </book>
  <book>
    <title>‚â‚³‚µ‚¢Java</title> 
    <img file="java.jpg"/>
  </book>
</books>
