<?xml version="1.0" encoding="Shift_JIS" ?>

<!DOCTYPE cars[
  <!ELEMENT cars           (car+)>
  <!ELEMENT car            (name, price)>
  <!ATTLIST car  id  CDATA #REQUIRED>
  <!ATTLIST car  country   (日本|USA) "日本">
  <!ELEMENT name           (#PCDATA)>
  <!ELEMENT price          (#PCDATA)>
]>

<cars>
  <car id="1001" country="日本">
    <name>乗用車</name>
    <price>150</price>
  </car>
  <car id="2001" country="日本">
    <name>トラック</name>
    <price>500</price>
  </car>
  <car id="1005">
    <name>オープンカー</name>
    <price>200</price>
  </car>
</cars>

