<?xml version="1.0" encoding="Shift_JIS" ?>

<!DOCTYPE cars[
  <!ELEMENT cars           (car+)>
  <!ELEMENT car            (name, price, group)>
  <!ELEMENT name           (#PCDATA)>
  <!ELEMENT price          (#PCDATA)>
  <!ELEMENT group          (#PCDATA)>
  <!ENTITY  cgroup         "自動車グループ">
]>

<cars>
  <car>
    <name>乗用車</name>
    <price>150</price>
    <group>&cgroup;</group>
  </car>
  <car>
    <name>トラック</name>
    <price>500</price>
    <group>&cgroup;</group>
  </car>
  <car>
    <name>オープンカー</name>
    <price>200</price>
    <group>&cgroup;</group>
  </car>
</cars>

