<?xml version="1.0" encoding="Shift_JIS" ?>

<!DOCTYPE cars[
  <!ELEMENT cars  (car+)>
  <!ELEMENT car   (name, price)>
  <!ELEMENT name  (#PCDATA)>
  <!ELEMENT price (#PCDATA)>
  <!ENTITY  new  SYSTEM "new.xml">
]>

<cars>
  <car>
    <name>乗用車</name>
    <price>150</price>
  </car>
  <car>
    <name>トラック</name>
    <price>500</price>
  </car>
  <car>
    <name>オープンカー</name>
    <price>200</price>
  </car>
  &new;
</cars>

