<?xml version="1.0" encoding="Shift_JIS" ?>

<!DOCTYPE cars[
  <!ELEMENT cars    (car+)>
  <!ELEMENT car     (name, sub?, price)>
  <!ELEMENT name    (#PCDATA)>
  <!ELEMENT sub     (#PCDATA)>
  <!ELEMENT price   (#PCDATA)>
]>

<cars>
  <car>
    <name>乗用車</name>
    <price>150</price>
  </car>
  <car>
    <name>トラック</name>
    <sub>業務用</sub>
    <price>500</price>
  </car>
  <car>
    <name>オープンカー</name>
    <sub>レジャー用</sub>
    <price>200</price>
  </car>
</cars>
