=== haruto-k/PC-Same-party/XML/やさしいXML/Sample/03/Sample.dtd
<?xml version="1.0" encoding="Shift_JIS" ?>

<!ELEMENT cars     (car+)>
<!ELEMENT car      (name, price)>
<!ELEMENT name     (#PCDATA)>
<!ELEMENT price    (#PCDATA)>

=== haruto-k/PC-Same-party/XML/やさしいXML/Sample/03/Sample8.xml
<?xml version="1.0" encoding="Shift_JIS" ?>

<!DOCTYPE cars SYSTEM "Sample.dtd">

<cars>
  <car>
    <name>乗用車</name>
    <price>150</price>
  </car>
  <car>
    <name>トラック</name>
    <price>500</price>
  </car>
  <car>
    <name>オープンカー</name>
    <price>200</price>
  </car>
</cars>
